name: movie_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  gap: ^3.0.1
  delayed_display: ^2.0.0
  shared_preferences: ^2.2.3
  get_it:
  dio: ^5.5.0+1
  glassmorphism: ^3.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  sizer: ^2.0.15
  smooth_page_indicator: ^1.2.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  google_nav_bar: ^5.0.6
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.1
  awesome_snackbar_content: ^0.1.3
  flutter_icon_snackbar: ^1.1.7
  location: ^6.0.2
  google_maps_flutter: ^2.5.3
  lottie: ^3.1.2
  shimmer: ^3.0.0
  share_plus: ^10.0.0
  image_picker: ^1.1.2
  hive: ^2.2.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - assets/

